In [1]:
# importing necessary libraries and commands

import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import chi2_contingency
import matplotlib.pyplot as plt

In [2]:
#Reading the Excel file with crash data and storeing on a variable

crashdata=pd.read_excel("Traffic_crashes.xlsx", sheet_name="Sheet1")

In [3]:
#showing some data rows to confirm

crashdata.head(10)

,Crash_ID,Year,Local_Report_Number,Severity,Functional_Class
0,20146089396,2014,140725434,(4) Injury Possible,Other Principal Arterial Roads
1,20156141007,2015,150981625,(3) Minor Injury Suspected,Other Principal Arterial Roads
2,20156113442,2015,150850217,(4) Injury Possible,Other Principal Arterial Roads
3,20146035108,2014,140249591,(3) Minor Injury Suspected,Minor Arterial Roads
4,20156125345,2015,150926699,(4) Injury Possible,Major Collector Roads
5,20156064738,2015,150460503,(4) Injury Possible,Other Principal Arterial Roads
6,20156127119,2015,150939091,(3) Minor Injury Suspected,Minor Arterial Roads
7,20146006115,2014,140049046,(3) Minor Injury Suspected,Other Principal Arterial Roads
8,20186072160,2018,180367271,(1) Fatal,Other Principal Arterial Roads
9,20146091597,2014,140705747,(4) Injury Possible,Other Principal Arterial Roads

In [4]:
# Cross Classifying the data on two basis (Severity and Functional CLass)

field1=crashdata['Severity']
field2=crashdata['Functional_Class']
crosst=pd.crosstab(field1, field2)
crosst

Functional_Class,Interstate Route,Local Roads,Major Collector Roads,Minor Arterial Roads,Other Principal Arterial Roads
Severity,,,,,
(1) Fatal,0,1,0,1,7
(2) Serious Injury Suspected,0,8,5,13,41
(3) Minor Injury Suspected,0,49,23,130,348
(4) Injury Possible,1,42,35,114,406

In [5]:
# the chi square test
# H0: There is no significant relationship between Crash Severity and Functional Class of Road (the variables are independent)
# H1: There is significant relationship between Crash Severity and Functional Class of Road (the variables are dependent)

In [6]:
# determining the values and displaying

chi2,pval,dof,ex_f=chi2_contingency(crosst)
print('Chi Square Value=', chi2)
print('p-value=', pval)
print('Degree of freedom=', dof)
print('Expected Frequency:', ex_f)

Chi Square Value= 11.081462328720033
p-value= 0.5219505635374502
Degree of freedom= 12
Expected Frequency: [[7.35294118e-03 7.35294118e-01 4.63235294e-01 1.89705882e+00
  5.89705882e+00]
 [5.47385621e-02 5.47385621e+00 3.44852941e+00 1.41225490e+01
  4.39003268e+01]
 [4.49346405e-01 4.49346405e+01 2.83088235e+01 1.15931373e+02
  3.60375817e+02]
 [4.88562092e-01 4.88562092e+01 3.07794118e+01 1.26049020e+02
  3.91826797e+02]]